version: '3'

services:
    #PHP Service
    laravel-scrubber:
        build:
            context: ""
            dockerfile: Dockerfile
        container_name: laravel-scrubber
        tty: true
        environment:
            SERVICE_NAME: laravel-scrubber
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - yorcreative

networks:
    yorcreative:
        driver: bridge

